# Generated by Django 6.0.1 on 2026-02-03 12:55

import users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
    ]
