# Generated by Django 6.0.1 on 2026-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_options_payment_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
