# Generated by Django 6.0.1 on 2026-02-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
