# Generated by Django 6.0.1 on 2026-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview_image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview_image",
            field=models.URLField(),
        ),
    ]
