# Generated by Django 6.0.1 on 2026-02-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
