# Generated by Django 6.0.1 on 2026-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_preview_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="materials/preview"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="materials/preview"
            ),
        ),
    ]
