# Generated by Django 6.0.1 on 2026-02-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_course_alter_lesson_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(),
        ),
    ]
